FROM python:3.12-slim
COPY ./backend /app/backend/
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app/backend
# Port for flask backend
EXPOSE 5000

CMD ["flask", "cli", "reindex"]
CMD ["flask", "run"]